# Generated by Django 2.1.5 on 2019-04-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
    ]
