# Generated by Django 2.1.5 on 2019-04-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
